language: ruby
rvm:
  - "2.5.0"
sudo: false
cache: bundler
env:
  # http://docs.travis-ci.com/user/environment-variables/#Global-Variables
  global:
    - BITCOINORG_BUILD_TYPE=deployment
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxygen/Doxyfile-dashdocs

before_install:
  - . $TRAVIS_BUILD_DIR/scripts/install-doxygen.sh
  - gem update --system
  - gem install bundler

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script: make travis

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: travisGHdeploy

  verbose: true
  local-dir: _site/
  repo: thephez/thephez.github.io
  target_branch: master

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x scripts/generateDocumentationAndDeploy.sh
  - ./scripts/generateDocumentationAndDeploy.sh
